# Generated by Django 2.2.11 on 2020-04-01 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='correct_question',
            field=models.IntegerField(default='1'),
            preserve_default=False,
        ),
    ]
