# Generated by Django 2.2.11 on 2020-04-01 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_question_correct_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='correct_question',
            new_name='correct_choice',
        ),
    ]
