# Generated by Django 2.2.11 on 2020-04-01 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0003_auto_20200401_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='selected_choice',
            field=models.IntegerField(default=1),
        ),
    ]
