# Generated by Django 2.2.11 on 2020-04-01 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0005_auto_20200401_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='correct_choice',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='selected_choice',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
