# Generated by Django 2.2.11 on 2020-04-02 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0006_auto_20200401_1752'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('question_id', models.IntegerField(default=1)),
                ('correct_choice', models.CharField(blank=True, max_length=200, null=True)),
                ('selected_choice', models.CharField(blank=True, max_length=200, null=True)),
                ('language', models.CharField(choices=[('ENG', 'English'), ('FR', 'Français')], max_length=30)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Choice',
            new_name='EnChoice',
        ),
        migrations.RenameModel(
            old_name='Question',
            new_name='EnQuestion',
        ),
        migrations.CreateModel(
            name='FrChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(max_length=200)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.FrQuestion')),
            ],
        ),
    ]
