# Generated by Django 2.2.11 on 2020-04-02 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0007_auto_20200402_1519'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enquestion',
            name='language',
        ),
        migrations.RemoveField(
            model_name='frquestion',
            name='language',
        ),
        migrations.AddField(
            model_name='enquestion',
            name='question_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='enquestion',
            name='correct_choice',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='enquestion',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='frquestion',
            name='correct_choice',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='frquestion',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
