# Generated by Django 2.2.11 on 2020-04-02 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0008_auto_20200402_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquestion',
            name='is_correct',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='frquestion',
            name='is_correct',
            field=models.IntegerField(default=0),
        ),
    ]
